<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <AssemblyName>trantion</AssemblyName>
    <RootNamespace>OneClickChineseMod</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\BepInEx_win_x64_5.4.23.4.zip" />
    <EmbeddedResource Include="Resources\BepInEx_win_x86_5.4.23.4.zip" />
    <EmbeddedResource Include="Resources\BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.755+3fab71a.zip" />
    <EmbeddedResource Include="Resources\BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.755+3fab71a.zip" />
    <EmbeddedResource Include="Resources\TMP_Font_AssetBundles.zip" />
    <EmbeddedResource Include="Resources\XUnity.AutoTranslator-BepInEx-5.4.4.zip" />
    <EmbeddedResource Include="Resources\XUnity.AutoTranslator-BepInEx-IL2CPP-5.4.4.zip" />
    <EmbeddedResource Include="Resources\XUnity.AutoTranslator-BepInEx-5.5.0.zip" />
    <EmbeddedResource Include="Resources\XUnity.AutoTranslator-BepInEx-IL2CPP-5.5.0.zip" />
    <EmbeddedResource Include="Resources\XUnity.AutoTranslator-BepInEx-5.5.2.zip" />
    <EmbeddedResource Include="Resources\XUnity.AutoTranslator-BepInEx-IL2CPP-5.5.2.zip" />
    <EmbeddedResource Include="Resources\XUnity.AutoTranslator-BepInEx-5.6.1.zip" />
    <EmbeddedResource Include="Resources\XUnity.AutoTranslator-BepInEx-IL2CPP-5.6.1.zip" />
    <EmbeddedResource Include="Resources\DeepSeekTranslate.dll" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Themes\Colors.xaml" />
    <Resource Include="Resources\Themes\Typography.xaml" />
    <Resource Include="Resources\Styles\ButtonStyles.xaml" />
    <Resource Include="Resources\Styles\InputStyles.xaml" />
    <Resource Include="Resources\Styles\CardStyles.xaml" />
    <Resource Include="Resources\Styles\TabStyles.xaml" />
    <Resource Include="Resources\Icons\VectorIcons.xaml" />
  </ItemGroup>

</Project>
